import type { Prediction } from './api'

const now = Date.now()
const DAY = 86_400_000

function iso(daysAgo: number, hour = 6): string {
  const d = new Date(now - daysAgo * DAY)
  d.setUTCHours(hour, 30, 0, 0)
  return d.toISOString()
}

/**
 * Pronósticos de demostración (datos reales capturados del scraper) que se
 * muestran mientras no haya Firebase/backend configurados. Cumplen la política
 * diaria: con "bastantes" pronósticos (>= threshold) se regalan 2, el resto
 * premium. Al configurar Firebase, la web usa los pronósticos publicados.
 */
export const DEMO_PREDICTIONS: Prediction[] = [
  {
    match_id: '4750520',
    league: 'LaLiga',
    home_team: 'Racing de Santander',
    away_team: 'Villarreal CF',
    kickoff: new Date().toISOString(),
    market: 'Gana el local',
    market_type: 'home_win',
    selection: 'local_gana',
    odds: 3.6,
    confidence: 0.9,
    basis: [{ label: 'Racing ganó', side: 'for', value: 'Racing ganó - 9/10 Últimos partidos' }],
    premium: false,
    created_at: iso(0),
  },
  {
    match_id: '999001',
    league: 'Liga Profesional Argentina - Clausura',
    home_team: 'River Plate',
    away_team: 'Argentinos Juniors',
    kickoff: new Date().toISOString(),
    market: 'Gana el local',
    market_type: 'home_win',
    selection: 'local_gana',
    odds: 4.2,
    confidence: 1,
    basis: [{ label: 'River Plate ganó', side: 'for', value: 'River Plate ganó - 10/10 Últimos partidos' }],
    premium: false,
    created_at: iso(0, 7),
  },
  {
    match_id: '999002',
    league: 'Brasileirão',
    home_team: 'Mirassol',
    away_team: 'Flamengo',
    kickoff: new Date().toISOString(),
    market: 'Ambos marcan',
    market_type: 'btts',
    selection: 'ambos_marcan',
    odds: 1.8,
    confidence: 1,
    basis: [{ label: 'Ambos equipos marcaron', side: 'for', value: 'Ambos equipos marcaron - 5/5 Últimos partidos' }],
    premium: true,
    created_at: iso(0, 8),
  },
  {
    match_id: '999003',
    league: 'Championship',
    home_team: 'Burnley',
    away_team: 'West Ham United',
    kickoff: new Date().toISOString(),
    market: 'Gana el local',
    market_type: 'home_win',
    selection: 'local_gana',
    odds: 2.3,
    confidence: 0.75,
    basis: [{ label: 'Burnley ganó', side: 'for', value: 'Burnley ganó - 3/4 Últimos partidos' }],
    premium: true,
    created_at: iso(0, 9),
  },
  {
    match_id: '999004',
    league: 'MLS',
    home_team: 'New York City FC',
    away_team: 'Philadelphia Union',
    kickoff: new Date().toISOString(),
    market: 'Gana el visitante',
    market_type: 'away_win',
    selection: 'visitante_gana',
    odds: 2.55,
    confidence: 1,
    basis: [{ label: 'Philadelphia Union ganó', side: 'for', value: 'Philadelphia Union ganó - 8/8 Últimos partidos' }],
    premium: true,
    created_at: iso(0, 10),
  },
  {
    match_id: '999005',
    league: 'Supercopa Francesa - Final',
    home_team: 'Lens',
    away_team: 'PSG',
    kickoff: new Date().toISOString(),
    market: 'Gana el visitante',
    market_type: 'away_win',
    selection: 'visitante_gana',
    odds: 1.75,
    confidence: 0.88,
    basis: [{ label: 'PSG ganó', side: 'for', value: 'PSG ganó - 7/8 Últimos partidos' }],
    premium: true,
    created_at: iso(0, 11),
  },
  {
    match_id: '999006',
    league: 'Brasileirão',
    home_team: 'Atlético Mineiro',
    away_team: 'Grêmio',
    kickoff: new Date().toISOString(),
    market: 'Gana el local',
    market_type: 'home_win',
    selection: 'local_gana',
    odds: 1.83,
    confidence: 0.75,
    basis: [{ label: 'Atlético Mineiro ganó', side: 'for', value: 'Atlético Mineiro ganó - 3/4 Últimos partidos' }],
    premium: true,
    created_at: iso(0, 12),
  },
  {
    match_id: '999007',
    league: 'Liga MX - Apertura',
    home_team: 'Club América',
    away_team: 'Atlético San Luis',
    kickoff: new Date().toISOString(),
    market: 'Ambos marcan',
    market_type: 'btts',
    selection: 'ambos_marcan',
    odds: 1.77,
    confidence: 0.83,
    basis: [{ label: 'Ambos equipos marcaron', side: 'for', value: 'Ambos equipos marcaron - 5/6 Últimos partidos' }],
    premium: true,
    created_at: iso(0, 13),
  },
]

/** Pronósticos de días anteriores para la sección Historial (modo demo). */
export const DEMO_HISTORY: Prediction[] = [
  {
    match_id: '998101',
    league: 'Premier League',
    home_team: 'Manchester City',
    away_team: 'Chelsea',
    kickoff: new Date(now - DAY).toISOString(),
    market: 'Gana el local',
    market_type: 'home_win',
    selection: 'local_gana',
    odds: 2.1,
    confidence: 0.87,
    basis: [{ label: 'Manchester City ganó', side: 'for', value: 'Manchester City ganó - 6/7 Últimos partidos' }],
    premium: true,
    created_at: iso(1, 6),
  },
  {
    match_id: '998102',
    league: 'Serie A',
    home_team: 'Inter',
    away_team: 'Napoli',
    kickoff: new Date(now - DAY).toISOString(),
    market: 'Ambos marcan',
    market_type: 'btts',
    selection: 'ambos_marcan',
    odds: 1.85,
    confidence: 0.92,
    basis: [{ label: 'Ambos equipos marcaron', side: 'for', value: 'Ambos equipos marcaron - 6/6 Últimos partidos' }],
    premium: false,
    created_at: iso(1, 7),
  },
  {
    match_id: '998103',
    league: 'Bundesliga',
    home_team: 'Bayern München',
    away_team: 'RB Leipzig',
    kickoff: new Date(now - DAY).toISOString(),
    market: 'Gana el local',
    market_type: 'home_win',
    selection: 'local_gana',
    odds: 2.45,
    confidence: 0.9,
    basis: [{ label: 'Bayern München ganó', side: 'for', value: 'Bayern München ganó - 8/9 Últimos partidos' }],
    premium: true,
    created_at: iso(1, 8),
  },
  {
    match_id: '998104',
    league: 'Ligue 1',
    home_team: 'Marseille',
    away_team: 'Lyon',
    kickoff: new Date(now - 2 * DAY).toISOString(),
    market: 'Más de 2.5 goles',
    market_type: 'over_2_5',
    selection: 'mas_de_2_5',
    odds: 1.78,
    confidence: 0.84,
    basis: [{ label: 'Más de 2.5 goles', side: 'for', value: 'Más de 2.5 goles - 5/6 Últimos partidos' }],
    premium: true,
    created_at: iso(2, 6),
  },
  {
    match_id: '998105',
    league: 'LaLiga',
    home_team: 'Real Madrid',
    away_team: 'Atlético Madrid',
    kickoff: new Date(now - 2 * DAY).toISOString(),
    market: 'Gana o empata local',
    market_type: 'home_or_draw',
    selection: 'local_gana_o_empata',
    odds: 1.72,
    confidence: 0.88,
    basis: [{ label: 'Real Madrid gana o empata', side: 'for', value: 'Real Madrid gana o empata - 7/8 Últimos partidos' }],
    premium: false,
    created_at: iso(2, 7),
  },
]